#!/bin/sh
set -e

MYNAKE=$(basename "$0")
GH_COMMAND=$(basename "${0}" | tr '-' ' ')
TOP=$(dirname "${0}")
COMMAND="${1}"

if [ $# -eq 0 ];then
  echo "Usage: ${GH_COMMAND} [command]"
  echo " ${GH_COMMAND} setup     # Build the Docker image"
  echo " ${GH_COMMAND} start     # Start a xeyes form the Docker container"
  echo " ${GH_COMMAND} shell     # Shell into the Docker container"
  exit
fi

if [ "${COMMAND}" = "setup" ]; then
  docker compose -f "${TOP}/docker-compose.yml" build
  exit 0
fi


if [ "${COMMAND}" = "start" ]; then
  shift
  docker compose -f "${TOP}/docker-compose.yml" run -d -q --rm gh-xeyes
  exit 0
fi
if [ "${COMMAND}" = "shell" ]; then
  shift
  # shell into the container
  docker compose -f "${TOP}/docker-compose.yml" exec gh-xeyes bash
fi